# Site settings
title: Mosaico.io News and Blog
email: info@mosaico.io
description: > # News from Mosaico Template Editor.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mosaico.io" # the base hostname & protocol for your site
staticurl: "http://gh.mosaico.io"
twitter_username: mosaicoeditor
github_username:  bago
permalink: /:categories/:title/
excerpt_separator: \n\n

# Build settings
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["footnotes", "smart", "hard_wrap", "no_intra_emphasis"]
